import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/Cmp/Navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
  <body className="font-body-md text-body-md selection:bg-primary/30">
  <div className="fixed inset-0 pointer-events-none z-0" id="particles-container"></div>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
